name: 'Completion Notification'
description: 'Notify Slack channel for Training & Cert that a learner completed the challenge.'
inputs:
  slack-webhook-url:
    description: 'URL for incoming webhooks to Slack channel'
    required: true
  repo-name:
    description: 'Name of the GitHub repo'
    required: true
  user-name:
    description: 'Name of the user'
    required: true
runs:
  using: 'node16'
  main: 'index.js'